Models/Album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace muscshop.Models
{
    public class Album
    {
        [Required(ErrorMessage = "Please, enter the title")]
        public string Title { get; set; }

        [Range(1, 300, ErrorMessage = "please enter price: 1 to 300")]
        public double Price { get; set; }

        public string AlbumUrl { get; set; }

        [Required(ErrorMessage = "ReleaseYear is required")]
        public int ReleaseYear { get; set; }

        public Artist Artist { get; set; }

        public Genre Genre { get; set; }

        public int AlbumId { get; set; }

        public string Description { get; set; } = "albumDescr";

        public int ArtistId { get; set; }

        public int GenreId { get; set; }
    }
}

Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace muscshop.Models
{
    public class Artist
    {
        public string Name { get; set; }

        public string BasicInfo { get; set; }

        public string ImageUrl { get; set; }

        public int ArtistId { get; set; }
    }
}

Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace muscshop.Models
{
    public class Genre
    {
        public string Name { get; set; }

        public int GenreId { get; set; }

        public List<Album> Albums { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace muscshop.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/StoreController.cs
using muscshop.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace muscshop.Controllers
{
    public class StoreController : Controller
    {
        // private static FakeDatabase _database = new FakeDatabase();

        StoreContext _storeContext = new StoreContext();
        // GET: Store
        public ActionResult Index()
        {
            var genres = _storeContext.Genres;
            // var genres = _database.Genres;
            return View(genres);
        }

        public ActionResult Browse(string genre)
        {
            var genreModel = _storeContext.Genres.Where(x => x.Name == genre).FirstOrDefault();

            var albums = _storeContext.Albums.Where(x => x.Genre.Name == genre).ToList();

            genreModel.Albums = albums;

            return View(genreModel);
        }

        public ActionResult Detail(int id)
        {
            var album = _storeContext.Albums.Where(x => x.AlbumId == id).FirstOrDefault();


            return View(album);
        }
    }
}

Controllers/StoreManagerController.cs
using muscshop.Context;
using muscshop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace muscshop.Controllers
{
    public class StoreManagerController : Controller
    {
        // private static FakeDatabase _database = new FakeDatabase();

        StoreContext _storeContext = new StoreContext();
        // GET: StoreManager
        public ActionResult Index()
        {
            var albums = _storeContext.Albums;

            return View(albums);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var album = _storeContext.Albums.Where(x => x.AlbumId == id).FirstOrDefault();
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(_storeContext.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(_storeContext.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        [HttpPost]
        public ActionResult Edit(Album updateAlbum)
        {

            if(ModelState.IsValid)
            {

                var oldAlbum = _storeContext.Albums.Where(x => x.AlbumId == updateAlbum.AlbumId).FirstOrDefault();

                oldAlbum.ReleaseYear = updateAlbum.ReleaseYear;
                oldAlbum.Title = updateAlbum.Title;
                oldAlbum.AlbumUrl= updateAlbum.AlbumUrl;
                oldAlbum.Price = updateAlbum.Price;
                oldAlbum.ArtistId = updateAlbum.ArtistId;
                oldAlbum.GenreId = updateAlbum.GenreId;
                oldAlbum.Description = updateAlbum.Description;
                _storeContext.SaveChanges();
                return RedirectToAction("index");
            }

            else
            {
                //var errors = ModelState.Values.Where(x => x.Errors.Count > 0);

                List<KeyValuePair<string, ModelState>> errorList = ModelState.Where(x => x.Value.Errors.Count > 0).ToList();

                ViewBag.ErrorList = errorList;

                return Edit(updateAlbum.AlbumId);

                //var album = _database.Albums.Where(x => x.AlbumId == updateAlbum.AlbumId).FirstOrDefault();
                //ViewBag.ArtistId = new SelectList(_database.Artists, "ArtistId", "Name", album.Artist.ArtistId);
                //ViewBag.GenreId = new SelectList(_database.Genres, "GenreId", "Name", album.Genre.GenreId);
                //return View(album);
            }

        }

        public ActionResult Create()
        {
            ViewBag.ArtistId = new SelectList(_storeContext.Artists, "ArtistId", "Name", 1);
            ViewBag.GenreId = new SelectList(_storeContext.Genres, "GenreId", "Name", 1);
            return View();
        }

        [HttpPost]
        public ActionResult Create(Album newalbum)
        {
            if (!ModelState.IsValid)
            {
                List<KeyValuePair<string, ModelState>> errorList = ModelState.Where(x => x.Value.Errors.Count > 0).ToList();

                ViewBag.ErrorList = errorList;
                return Create();
            }



            _storeContext.Albums.Add(newalbum);
            _storeContext.SaveChanges();

            return RedirectToAction("index");
            
        }

        public ActionResult DeleteAlb(int id)
        {
            var deletealbum = _storeContext.Albums.Find(id); ;
            _storeContext.Albums.Remove(deletealbum);
           
            _storeContext.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Search(string parameter)
        {
            var albums = _storeContext.Albums.Where(x => x.Title.ToLower().Contains(parameter.ToLower()));

            return View("index", albums);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Store/Browse.cshtml
@model muscshop.Models.Genre

@{
    ViewBag.Title = "Browse";
}

<h2>Browse</h2>


<div>
    <h3><em>@Model.Name</em> Albums</h3>
    <ul>
        @foreach (var album in Model.Albums)
        {
            <li>
                <a href="/Store/Detail/@album.AlbumId">
                    <img src="@album.AlbumUrl" alt="@album.Title" width="200" height="200" />
                    <span>@album.Title</span>
                </a>
            </li>
            <br>
        }

    </ul>
</div>

Views/Store/Detail.cshtml
@model muscshop.Models.Album

@{
    ViewBag.Title = "Detail";
}

<center>
 <h2>@Model.Title</h2>
<img src="@Model.AlbumUrl" alt="@Model.Title" width="300" height="300"/>
<p class="mt-5"><em>Artist:</em> @Model.ArtistId</p>
<p><em>Genre:</em> @Model.GenreId</p>
<p><em>Price:</em> @Model.Price</p>
<p><em>Year:</em> @Model.ReleaseYear</p>
<p><em>Info:</em> @Model.Description</p>
</center>


Views/Store/Index.cshtml
@model IEnumerable <muscshop.Models.Genre>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>Select from @Model.Count()</p>

<ul>
    @foreach (var genre in Model)
    {
        <li><a href="/Store/Browse?genre=@genre.Name">@genre.Name</a></li>
 
    }
</ul>

Views/StoreManager/Create.cshtml
@model muscshop.Models.Album

@{
    ViewBag.Title = "Create new";

    var genres = (SelectList)ViewBag.GenreId;
    var artists = (SelectList)ViewBag.ArtistId;
}

<h2>Create new</h2>
@{
    var errors = ViewBag.ErrorList as List<KeyValuePair<string, ModelState>>;
}

@using (Html.BeginForm("Create", "StoreManager", FormMethod.Post))
{
    <div class="form-horizontal">

        <div class="form-group">
            <label class="control-label col-md-2">Artist</label>
            <div class="col-md-10">
                <select class="form-control" id="ArtistId" name="ArtistId">
                    @foreach (var item in artists)
                    {
                        if (int.Parse(item.Value) == 1)
                        {
                            <option selected="selected" value="@item.Value">@item.Text</option>
                        }
                        else
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Genre</label>
            <div class="col-md-10">
                <select class="form-control" id="GenreId" name="GenreId">
                    @foreach (var item in genres)
                    {
                        if (int.Parse(item.Value) == 1)
                        {
                            <option selected="selected" value="@item.Value">@item.Text</option>
                        }
                        else
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Price</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="Price" value="" ? />
                @if (errors != null && errors.Where(x => x.Key == "Price").Count() > 0)
                {
                    foreach (var e in errors.FirstOrDefault(x => x.Key == "Price").Value.Errors)
                    {
                        <span class="text-danger">
                            @e.ErrorMessage
                        </span>
                    }
                }
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Title</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="Title" value="" ? />
                @if (errors != null && errors.Where(x => x.Key == "Title").Count() > 0)
                {
                    foreach (var e in errors.FirstOrDefault(x => x.Key == "Title").Value.Errors)
                    {
                        <span class="text-danger">
                            @e.ErrorMessage
                        </span>
                    }
                }
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">URL</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="AlbumUrl" value="" ? />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">RelYEar</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="ReleaseYear" value="" ? />
                @if (errors != null && errors.Where(x => x.Key == "ReleaseYear").Count() > 0)
                {
                    foreach (var e in errors.FirstOrDefault(x => x.Key == "ReleaseYear").Value.Errors)
                    {
                        <span class="text-danger">
                            @e.ErrorMessage
                        </span>
                    }
                }
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Description</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="Description" value="" ? />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SAVE" class="btn btn-danger" />
            </div>
        </div>
    </div>

}
  
@Html.ActionLink("Back", "index")

Views/StoreManager/Edit.cshtml
@model muscshop.Models.Album

@{
    ViewBag.Title = "Edit";

    var genres = (SelectList)ViewBag.GenreId;
    var artists = (SelectList)ViewBag.ArtistId;
}

<h2>Edit</h2>

@{
    var errors = ViewBag.ErrorList as List<KeyValuePair<string, ModelState>>;
}

@using (Html.BeginForm("Edit", "StoreManager", FormMethod.Post))
{
    <div class="form-horizontal">

        <div class="form-group">
            <label class="control-label col-md-2">Artist</label>
            <div class="col-md-10">
                <select class="form-control" id="ArtistId" name="ArtistId">
                    @foreach (var item in artists)
                    {
                        if (item.Text == Model.Artist.Name)
                        {
                            <option selected="selected" value="@item.Value">@item.Text</option>
                        }
                        else
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Genre</label>
            <div class="col-md-10">
                <select class="form-control" id="GenreId" name="GenreId">
                    @foreach (var item in genres)
                    {
                        if (item.Text == Model.Genre.Name)
                        {
                            <option selected="selected" value="@item.Value">@item.Text</option>
                        }
                        else
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Price</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="Price" value="@Model.Price" ? />
                @if (errors != null && errors.Where(x => x.Key == "Price").Count() > 0)
                {
                    foreach (var e in errors.FirstOrDefault(x => x.Key == "Price").Value.Errors)
                    {
                        <span class="text-danger">
                            @e.ErrorMessage
                        </span>
                    }
                }
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Title</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="Title" value="@Model.Title" ? />
                @if (errors != null && errors.Where(x => x.Key == "Title").Count() > 0)
                {
                    foreach (var e in errors.FirstOrDefault(x => x.Key == "Title").Value.Errors)
                    {
                        <span class="text-danger">
                            @e.ErrorMessage
                        </span>
                    }
                }
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">URL</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="AlbumUrl" value="@Model.AlbumUrl" ? />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Description</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="Description" value="@Model.Description" ? />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">RelYEar</label>
            <div class="col-md-10">
                <input type="text" class="form-control" name="ReleaseYear" value="@Model.ReleaseYear" ? />
                @if (errors != null && errors.Where(x => x.Key == "ReleaseYear").Count() > 0)
                {
                    foreach (var e in errors.FirstOrDefault(x => x.Key == "ReleaseYear").Value.Errors)
                    {
                        <span class="text-danger">
                            @e.ErrorMessage
                        </span>
                    }
                }
            </div>
        </div>
        <input id="AlbumId" name="AlbumId" type="hidden" value="@Model.AlbumId" />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SAVE" class="btn btn-danger" />
            </div>
        </div>
    </div>

}

@Html.ActionLink("Back", "index")

Views/StoreManager/Index.cshtml
@model IEnumerable <muscshop.Models.Album>

@{
    ViewBag.Title = "Index";
}
<br>
<form action="/StoreManager/Search" method="get">
    <input type="text" name="parameter" placeholder="Title"/>
    <input type="submit" value="Search"/>
</form>

<br>
<a href="/StoreManager/Create">Create New</a>
<br>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Price</th>
        <th>AlbumUrl</th>
        <th>Release Year</th>
        <th>Description</th>

    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>@item.Title</td>
    <td>@item.Price</td>
    <td>@item.AlbumUrl</td>
    <td>@item.ReleaseYear</td>
    <th>@item.Description</th>
    <td>@Html.ActionLink("Edit", "Edit", new { id = item.AlbumId })</td>
    <td>@Html.ActionLink("Delete", "DeleteAlb", new { id = item.AlbumId })</td>
</tr>
    }

</table>